### PR TITLE
Add support for typography weight

### PR DESCRIPTION
**Pull request by gabrieltomescu**
@nolastan I'm trying to add support for font weights as well. I updated the code and my Google Sheet, but it doesn't seem to be parsing it.

Any ideas on what's missing?

### CODE REVIEW

**Comment by gabrieltomescu** [comment]
@nolastan I'm trying to add support for font weights as well. I updated the code and my Google Sheet, but it doesn't seem to be parsing it. 

Any ideas on what's missing?

**Comment by gabrieltomescu** [comment]
Ahh, it's not exposed? http://developer.sketchapp.com/reference/MSTextLayer/

Bummer.

**Comment by nolastan** [comment]
Each weight is actually a different font file on your computer. See the template for an example on how to use with Arial.

**Comment by gabrieltomescu** [comment]
@nolastan Nice! That worked. Thanks.

**Comment by nolastan** [comment]
Added a section on this to the readme to help others.

**Pull request closed without merging**
